---
title: "General Discussion"
output: pdf_document
---

Modern views on selective attention and cognitive control often bin processing into dichotomies like controlled/automatic, top-down/bottom-up, and endogenous/exogenous. Theoretical treatments of attention, however, have often included a third kind of attentional control whereby attention is guided by internal memory representations created through experience. Though they rarely elaborate on how such memory systems would operate and instead vaguely appeal to associative learning principles. More recent empirical work has also demonstrated that prior experiences can influence selective attention in a seemingly automatic, stimulus-driven manner. This evidence has been difficult to reconcile with dichotomous frameworks of cognitive control [@botvinick_evaluating_2001; @braver_variable_2012; @de_pisapia_model_2006; @chiu_cortical_2019; @jiang_bayesian_2014]. 

Based on these theoretical and empirical gaps, I argued that there is a need to examine attention using a memory-based framework and proposed an instance-based memory theory. The instance theory of automatic attentional control relies on four assumption (e.g., Logan, 1988; Hintzman, 1984): (1) \textit{obligatory memory encoding}; (2)  \textit{"instance" or "exemplar" memory representation}; (3) \textit{obligatory memory retrieval}; and (4) \textit{the preservation of cognitive processing details}. The current thesis investigated general principles of the instance theory using a converging operations approach. 

To further situate the contribution of the thesis, the following sections will briefly discuss the findings of the empirical work and their implications for theories of attention and cognitive control. In the first section, I will briefly summarize the critical aspects of the empirical findings in the thesis. Following that, I will discuss some limitations and open questions regarding the instance theory and automatic attentional control. Finally, I will discuss some broader implications of the current thesis.

# Summary of empirical chapters

In Chapter 2, I investigated the obligatory nature of memory encoding of attentional control. In the selective attention domain, the gold-standard measures of attention are conflict paradigms, like the Stroop [-@stroop_studies_1935] and flanker [@eriksen_effects_1974] tasks. Learning associations between context cues and selective attention, using these tasks, are thought to occur implicitly, without awareness, and in an obligatory fashion. However, these tasks present a very specific situation where a distracting irrelevant dimension interferes with our ability to attend to the relevant dimension. Here, I looked at whether participants would learn context-specific attentional control strategies in a novel bi-dimensional sampling task. I found participants did not spontaneously learn context-specificity. Instead, participants had to be instructed to adopt context-specific attentional strategies before any learning occurred. 

There were two important differences between my task and traditional congruency tasks. First, there was no conflict between the two dimensions, in the traditional sense, and both dimensions were task-relevant. Second, attentional selection occurred after the presentation of the target stimulus [e.g., @sperling_information_1960]. The finding that learning was not spontaneous suggests that learning context-attention associations is not error-driven, but requires participants to be engaged in the attentional strategy before, or while the target stimulus is presented. 

In Chapter 3, I investigated the long-term preservation of single experiences with conflict. One of the more distinguishing predictions made by the instance theory is that single experiences are preserved in the long-term and, if retrieved from memory, can produce automatic attentional control. Most theories of automatic attentional control, in contrast, propose that automaticity requires extensive practice [e.g., @schneider_controlled_1977; @shiffrin_controlled_1977; @treisman_strategies_1969]. Here, I used a large set of unique context items to determine whether a single experience applying attentional control on an item can influence a second presentation after many intervening trials. If so, I predicted a pattern of results similar to the congruency sequence effect. Across three experiments I found evidence that single experiences can influence selective attention after many intervening trials (4 to 319). However, I also note some boundary conditions, failing to find such effects when the repeated items differed in superficial details (color). 

In Chapter 4, I investigated how automatic attention could be controlled by manipulating memory-retrieval via task-relevance. Automaticity, according to the instance theory, is a memory-retrieval process. This suggests that there should be some flexibility in whether learning is expressed depending on which features of the environment are used to cue memory. In this chapter, I examined whether manipulating the relevance of context features would cause changes in context-dependent attentional control. 

I adopted a paradigm similar to the context-specific proportion congruent (CSPC) transfer design. However, unlike previous CSPC designs where contexts were defined by a single discriminating feature (e.g., upper vs. lower screen locations), contexts were defined by two feature dimensions and critically, the frequency unbiased context (50% congruent) always shared a feature with each of the frequency-biased contexts (0% and 100% congruent). To manipulate which overlapping feature was task-relevant I used a secondary counting task. Halfway through the experiment participants received new instructions, changing the task-relevant context feature. Across three different stimulus sets, I found that changing the task-relevance caused predictable changes in the congruency effects. This result implicates an important role for task-relevance in producing and manipulating context-dependency in complex environments.

# Re-evaluating the instance theory of automatic attentional control

The central aim of the current thesis was to evaluate general principles of the instance theory of automatic attention as it applies to selective attention. One fundamental question then, is whether the presented body of empirical work provides evidence for the instance theory of automatic attentional control. The answer, in my view, is both yes and no. The evidence provided here certainly is \textit{consistent} with an instance theory. Whether all possible alternative explanations can be ruled out is more difficult to say. Part of the problem is that most theories of automatic attention are vague, so it is difficult to determine what kinds of predictions they would make. I do think the evidence here however, is more consistent with the predictions made by an instance theory than any of ther alternatives.

For one, theories of learning and attention posit practice as the single most important pre-requisite for automaticity [e.g., @logan_toward_1988; @schneider_controlled_1977; @shiffrin_controlled_1977; @treisman_strategies_1969]. Under the instance theory, the role of practice is more nuanced. Automaticity from this perspective is not about laying down a certain number of memory traces, but instead about how easily those memory traces are retrieved. On the one hand, if memory retrieval is inefficient or difficult, many memory traces might be required for automaticity to develop. On the other hand, if a single memory is distinctive enough to support efficient retrieval, it should produce automatic attentional control. This is exactly what I found in Chapter 3: single, distinctive experiences were sufficient to influence performance in a selective attention task after many intervening trials. 

Second, theories of learning and attention posit that once automaticity develops it is difficult to suppress or modify. They seem to be suggesting, on the one hand, that automatic processes become hardwired and the mere presence of a stimulus should trigger its associated attentional control in a ballistic, rigid manner. On the other hand, they also suggest that these automatic processes can be controlled under some circumstances but do not make any predictions about when automatic processes can be controlled or explain how [e.g., @logan_toward_1988; @posner_attention_1975; @posner_facilitation_1975; @schneider_controlled_1977; @shiffrin_controlled_1977]. 

The instance theory in contrast, allows associations to form between stimuli and attentional control -- by way of encoding multiple memory traces -- but also makes predictions about whether that learning will be expressed in subsequent experiences which is dictated by memory retrieval. The extent to which automaticity can be controlled then, is determined by the extent to which memory retrieval can be controlled (e.g., Logan, 1988; 1992). In Chapter 4, I demonstrated that participants learned an association between contextual cues and attentional control in the first block of trials. Then, by shifting which features were task-relevant, demonstrated that participants could ignore the previous block and learn a new association. This result would be difficult to reconcile with the view that once learned, automaticity is difficult to modify, but easily accommodated by an instance theory. Under this view, by making some features task-relevant, I was modifying which features of the stimuli were being used to cue memory and dictating which prior experiences were being retrieved.

However, there is still no conclusive evidence for the instance theory's key assumption: instance representation. Although Chapter 3 presented evidence that single experiences can influence selective attention, this does not provide evidence that every experience is stored in a separate memory trace. It seems likely that associative learning could account for all the data provided here without this assumption. Associative learning differs from the instance theory in that learning is modeled as the gradual accumulation of excitatory or inhibitory connections between stimulus units. The associative strength is summative and represents the entire history of learning [e.g., @rescorla_theory_1972]. If taken at face value, this would separate learning from memory and implies that learners do not remember the events of separate trials or experiences, which seems quite extreme [e.g., @fagot_evidence_2006; @miller_assessment_1995; @vaughan_pigeon_1984; @voss_long-term_2009]. However, others have argued that the underlying architectures of associative and exemplar models are homogulous and the "structures of current associative learning being just graphical depictions of relationships ... common to both kinds of theory" [@estes_cognitive_1991, p. 11]. In which case the summative representation is more of a computational convenience than a theoretical statement about memory representation. In either case, associative learning models are similar enough to exemplar models that they could produce the same kinds of predictions [e.g., @blough_context_1998; @jamieson_instance_2012; @jamieson_memory-based_2010], but without assuming instance representation. 

# Limitations and open questions

## The limitations of verbal theories

Although the evidence is consistent with an instance theory, it is difficult to rule out all possible alternative explanations for the data presented. In part, this difficulty is due to the limitations of verbal or descriptive theories. This issue is most apparent in Chapter 3, where I discussed a variety of alternative theoretical explanations for the long-term congruency sequence effect. The long-term congruency sequence effect was an interesting finding that was predicted by the instance theory. However, many theories could also accommodate the finding with only small adjustments. This is one limitation of verbal theories: Verbal theories are inherently flexible, open to interpretation and difficult to falsify. 

Take for example the feature integration theory of congruency sequence effects [@hommel_event_1998; @hommel_feature-integration_2004; @hommel_theory_2001]. Here is a theory developed to explain trial-to-trial adjustments of the congruency effect using an event-binding model [e.g., @kahneman_reviewing_1992]. This theory explains congruency sequence effects as the result of a process attempting to bind sequential events together and makes no assumptions about long-term storage. However, because the theory does not state any explicit assumptions about long-term preservation, it is open to interpretation, and if one wanted to allow for long-term storage, then it could accommodate long-term effects. In effect, both the existence and non-existence of long-term phenomena would be consistent with this theory.

A second, related, limitation is that verbal theories are under-specified and do not make very precise predictions. This makes it difficult to determine whether data are consistent with the theory. In Chapter 3 for example, the long-term congruency sequence effect was found when the prime and probe shared colors, but disappeared when the colors of the images changed from prime to probe. Unfortunately, it is not clear whether that result is consistent or inconsistent with the instance theory. The instance theory makes the broad prediction that the currently presented stimulus will cue the retrieval of similar items in memory. It does not however, make precise predictions about how similar items need to be for retrieval. So, if we accept that changing colors reduces similarity to the point of impaired retrieval, the data are still consistent with the instance theory. 

Overall, I think the instance theory provides a good theoretical framework to assess the role of memory in guiding selective attention. To generate further predictions however, I think it will be necessary to refine the theory to formulate more concrete hypotheses and finer predictions. One possible route is to develop computational models that better specify the hypothesized mechanisms that underlie memory encoding, storage, and retrieval. For instance, there are open questions about how memories are aggregated on retrieval. It is unclear from the current theory, what to predict after multiple exposures to the same stimulus. Some exemplar models conceptualize retrieval as a race which retrieves a single memory trace [@logan_toward_1988], others as an accumulation of evidence, weighted by similarity [@palmeri_exemplar_1997], and others still as similarity-based aggregation [@hintzman_minerva_1984]. Therefore, one path forward is to use these computational models to better refine the instance theory and generate new hypotheses. 

## Do we need to assume attentional control settings are preserved in memory?

One of the general assumptions of the instance theory of automatic attentional control is that processing details are preserved in memory [@kolers_procedures_1984; @melton_associative_1972]. It is worth considering whether this assumption is necessary to explain the influence of prior experience on selective attention. One alternative is that associations form between stimuli and diagnostic features of attentional priority. For instance, a stimulus might be frequently paired with a reward. The re-presentation of that stimulus could trigger the retrieval of prior experiences, indicating that it was rewarded in the past, and attention prioritizes its processing based on that retrieved reward. Here, we do not need to assume that the attentional priority per se was stored and retrieved, but instead the level of reward was stored and retrieved and used as a diagnostic feature for determining attentional priority. Other features like predictiveness and conflict could be used in a similar manner. This approach suggests that the attentional control system uses some set of pre-defined diagnostic features to determine priority and when memory encodes experiences they are tagged with associated features.

We need not stop there however. If we assume that all features of the experience are stored in a memory trace, then prior experiences can be evaluated on any dimension \textit{after} retrieval. That is to say we do not need to assume that the level of reward is stored if we assume that the stimulus, response, and outcome are stored together. Whether the outcome was rewarding can be assessed after retrieval. Similarly, if the word RED in a blue colored font is stored in memory, then it does not need to store an associated level of 'conflict' because it can be evaluated for conflict after retrieval. This is actually consistent with the conflict-monitoring model, that assumes there is a dedicated cognitive process for evaluating the current level of conflict and triggering adjustments in control [@botvinick_evaluating_2001; @braver_variable_2012; @de_pisapia_model_2006]. It need only be extended to evaluate the conflict of retrieved prior experiences as well as the currently experienced conflict.  

In some ways, these approaches are more easily reconciled with traditional views of controlled and automatic processes than the instance theory. Attention, from these perspectives, is a controlled process and does not need to become automatic. Instead, the attentional control process leverages evidence from prior experiences to help determine attentional prioritization. For example, if the word RED in blue colored font retrieves many experiences that contain conflict, then the current experience feels more conflicting than if it did not retrieve experiences containing conflict. Attention is adjusted in response to the experienced conflict and experienced conflict is influenced by both the currently presented stimulus and memory. This differs from the instance theory which proposes that an attentional response is automatically reinstated, circumventing executive control entirely [e.g., @logan_attention_2005; @moors_automaticity_2006; @schneider_controlled_1977; @shiffrin_controlled_1977].

One inherent problem for these kinds of approaches however, is that they do not provide a mechanism for indicating how attention should be adjusted, only when attention should be adjusted. For example, if the word RED in blue colored font triggers a need for control, because of experienced/retrieved conflict, how does the attention system know that the color dimension should be prioritized and the word dimension ignored? The instance theory obviously does not have this issue because attentional control priorities are stored in memory. 

Additionally, the instance theory is the most general account because it assumes all cognitive processing details are preserved. Therefore, any cognitive control procedure can be stored and retrieved without the need to identify specialized diagnostic features (e.g., predictiveness, conflict) or specialized monitoring processes (e.g., the conflict-monitor). The instance theory then, can accommodate other cognitive control phenomena that have shown long-term contextual control effects (e.g., visual search, task-switching, negative priming, etc.) by appealing to the same underlying mechanisms. So although there does seem to be plausible alternatives to the assumption that cognitive procedures are stored and reinstated, the instance theory still seems like the most parsimonious and general account.


## Do we actually need three kinds of attentional control?

Traditionally, theories of attentional control assert a dichotomy between top-down and bottom-up control. The former reflecting current goals and the latter reflecting physical salience of the stimuli. I, as well as many others, have argued that there is a need for third kind of attentional control reflecting the influence of prior experiences; an automatic or memory-guided attentional control [e.g., @awh_top-down_2012; @egner_creatures_2014; @failing_selection_2018; @hutchinson_memory-guided_2012]. Again, here I consider whether this assumption is necessary.

One alternative, not previously entertained, is that bottom-up attentional control and memory-guided attentional control both reflect learned attentional priorities. Primitive physical features of our environment like sudden onsets, loud noises, or high contrast objects, are thought to automatically capture attention. It might be the case that these low level features have become associated with high attentional priority through experience. Evidence for this comes from work showing that bottom-up attentional capture is subject to top-down control similar to other automatic, learned behaviors [e.g., @anderson_variations_2010; @eimer_involuntary_2008; @folk_involuntary_1992]. 

Additionally, some models of attention [@kahneman_attention_1973; @schneider_controlled_1977; @shiffrin_controlled_1977] allow automatic attention to interject at any point during perceptual processing. Accordingly, early perceptual processing could cue memory with primitive features directing attention automatically before the stimuli are even fully processed. The strength by which some features of our environment seem to direct our attention automatically (e.g., the sudden appearance of a new object) might simply reflect extensive experience or how early in perceptual processing memory is cued. Therefore, it seems plausible, at least on the surface, that all bottom-up attentional phenomena could reflect the same memory-retrieval process as the one proposed here.

# Broader implications

A global aim of this empirical work is to determine how memory for specific prior experiences guides performance in the present moment. In the current thesis, I have outlined a theoretical framework describing how memory could influence cognitive control in an automatic, stimulus-driven manner. The empirical work presented here, together with the prior research, lends support this theory. The instance theory is a general theory of how control processing can be preserved and automatically reinstated. As such, it has implications for theories of cognitive control more generally. Furthermore, a better understanding of how memory for prior experiences can influence cognitive control may have more practical implications.

In everyday life, we would expect that memory for prior cognitive control operations routinely optimizes performance. When in familiar environments, people would gain the benefit of applying memory-based procedures for regulating the flow of information without the effortful cost of deliberation. These insights could be important for how we think about training in tasks where learning and attention are critically important. For instance, an important task for airport security is to use x-rays to screen baggage for dangerous items [e.g., @biggs_improving_2015; @mccarley_visual_2004; @wolfe_visual_2010]. This is an extremely attention-demanding task and resembles a variety of laboratory phenomena (e.g., visual search, congruency effects, vigilance/mind-wandering). Developing expertise could be streamlined if we know which kinds of experiences facilitate the development of automaticity. For instance, a few easily retrievable, context-rich experiences might improve training compared to many, poorly-defined experiences. Furthermore, developing generalization might require different kinds of training procedures.   

Additionally, problems in regulating the flow of information can result from the inappropriate use of, or failure to rely on memory. For example, deliberate control may need to override memory based control when memory-guided procedures are inappropriate yet the environment acts as a strong cue. Or, when memory fails to encode or retrieve cognitive control procedures, people may be forced to rely on taxing voluntary control processes to supply the control. Evaluating deficits in executive functioning and cognitive control using a memory-based framework could provide important insights from a clinical perspective. 

For instance, many clinical disorders like obsessive compulsive disorder (OCD) and attention-deficit/hyperactivity disorder (ADHD) are associated with difficulties selectively attending, shifting attention, inhibiting inappropriate responses, and slowed motor response. These difficulties are typically explained as deficits in executive functioning [@olley_memory_2007; @snyder_obsessive-compulsive_2015]. However, they could reflect deficits in memory based control. For example, what appears to be the inability to suppress unwanted behaviors, or to inhibit irrelevant information, might reflect an inability to properly contextualize task-relevant information, triggering automatic attentional responses to task-irrelevant cues. Similarly, overall slow motor responses could reflect a failure to retrieve cognitive control procedures, forcing people to rely on slow, taxing voluntary control processes.    
